apiVersion: "nuclio.io/v1beta1"
kind: "Function"
metadata:
  name: {{ template "nuclio-ci.releaseNode" . }}
spec:
  env:
    - name: PGINFO
      value: postgres:pass@172.17.0.1:5432
  runtime: "python"
  handler: "release_node:handler"
  triggers:
    httpTrigger:
      maxWorkers: 4
      kind: "http"
      attributes:
        port: 36550
  build:
    commands:
    - "apk add --update --no-cache gcc musl-dev python-dev postgresql-dev"
    - "pip install psycopg2 parse requests"
